import "./globals.css";
import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import Header from "@/components/Header"; //

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        // className={`${inter.className} ${notoSansJp.className} antialiased bg-background text-text-default`}
        className={`antialiased bg-background text-text-default`}
      >
        <Header />
        <main className="container mx-auto px-4 py-8"> {/* 左右の余白とページ全体の上下パディング */}
          {children} {/* 各ページのコンテンツがここにレンダリングされます */}
        </main>
      </body>
    </html>
  );
}
